'use client';

import { CalendarClock, CheckCircle2, PauseCircle, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useMyPlayerTrial } from '@/hooks/use-player-trials-api';
import { useLocaleStore } from '@/store/locale-store';

export default function PlayerTrialPage() {
  const english = useLocaleStore((state) => state.locale) === 'en';
  const workspace = useMyPlayerTrial();
  const data = workspace.data;
  const trial = data?.trial;
  if (workspace.isLoading) return <p className="text-sm text-muted-foreground">{english ? 'Loading trial...' : 'Carregando trial...'}</p>;
  if (!trial) return <Card><CardContent className="p-6"><h1 className="font-[var(--font-cinzel)] text-2xl font-bold">{english ? 'No published trial' : 'Nenhum trial publicado'}</h1><p className="mt-2 text-sm text-muted-foreground">{english ? 'If Staff starts an evaluation, its objective and criteria will appear here before any decision.' : 'Se a Staff iniciar uma avaliacao, objetivo e criterios aparecerao aqui antes de qualquer decisao.'}</p></CardContent></Card>;
  const active = ['ACTIVE', 'EXTENDED', 'PAUSED'].includes(data.effectiveStatus ?? trial.status);
  return <div className="space-y-6"><div><p className="text-sm uppercase text-primary">{english ? 'Transparent evaluation' : 'Avaliacao transparente'}</p><h1 className="font-[var(--font-cinzel)] text-3xl font-bold">{english ? 'Your trial' : 'Seu trial'}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{english ? 'Published criteria, factual check-ins, and a reasoned human decision. This does not change loot rules.' : 'Criterios publicados, check-ins factuais e decisao humana com motivo. Isso nao altera as regras de loot.'}</p></div>
    <div className="grid gap-3 md:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Status</p><Badge tone={data.effectiveStatus === 'PAUSED' ? 'blue' : active ? 'gold' : trial.status === 'APPROVED' ? 'green' : 'red'}>{data.effectiveStatus ?? trial.status}</Badge></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">{english ? 'Planned period' : 'Periodo previsto'}</p><p className="mt-1 text-sm font-semibold">{new Date(trial.plannedStartAt).toLocaleDateString()} - {new Date(trial.plannedEndAt).toLocaleDateString()}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">{english ? 'Adjusted end' : 'Fim ajustado'}</p><p className="mt-1 text-sm font-semibold">{data.adjustedEndAt ? new Date(data.adjustedEndAt).toLocaleDateString() : '-'}</p><p className="text-xs text-muted-foreground">{data.pausedDays ?? 0} {english ? 'absence day(s)' : 'dia(s) de ausencia'}</p></CardContent></Card></div>
    {data.pause ? <Card className="border-blue-400/30"><CardContent className="flex gap-3 p-4"><PauseCircle className="h-5 w-5 text-blue-300" /><div><p className="font-semibold">{english ? 'Trial paused by declared absence' : 'Trial pausado por ausencia declarada'}</p><p className="text-sm text-muted-foreground">{new Date(data.pause.startsAt).toLocaleDateString()} - {new Date(data.pause.endsAt).toLocaleDateString()}</p></div></CardContent></Card> : null}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" />{english ? 'Objective' : 'Objetivo'}</CardTitle></CardHeader><CardContent><p>{english ? trial.objectiveEn : trial.objectivePt}</p></CardContent></Card>
    <Card><CardHeader><CardTitle>{english ? 'Criteria published before evaluation' : 'Criterios publicados antes da avaliacao'}</CardTitle></CardHeader><CardContent className="space-y-3">{trial.criteria.map((criterion) => <div key={criterion.id} className="rounded-md border border-white/10 p-3"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /><p className="font-semibold">{english ? criterion.titleEn : criterion.titlePt}</p><Badge tone={criterion.isRequired ? 'gold' : 'blue'}>{criterion.isRequired ? (english ? 'Required' : 'Obrigatorio') : (english ? 'Optional' : 'Opcional')}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{english ? criterion.descriptionEn : criterion.descriptionPt}</p></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary" />Check-ins 7/14/30</CardTitle></CardHeader><CardContent className="space-y-3">{trial.checkIns.length ? trial.checkIns.map((checkIn) => <div key={checkIn.id} className="rounded-md border border-white/10 p-3"><p className="font-semibold">D{checkIn.day} · {checkIn.completedAt ? new Date(checkIn.completedAt).toLocaleDateString() : '-'}</p><p className="mt-1 text-sm text-muted-foreground">{english ? checkIn.bodyEn : checkIn.bodyPt}</p></div>) : <p className="text-sm text-muted-foreground">{english ? 'No factual check-in recorded yet.' : 'Nenhum check-in factual registrado ainda.'}</p>}</CardContent></Card>
    {trial.decisionReasonPt ? <Card><CardHeader><CardTitle>{english ? 'Decision and reason' : 'Decisao e motivo'}</CardTitle></CardHeader><CardContent><p>{english ? trial.decisionReasonEn : trial.decisionReasonPt}</p><p className="mt-2 text-xs text-muted-foreground">{english ? 'Human decision; no automatic punishment or loot effect.' : 'Decisao humana; sem punicao automatica ou efeito em loot.'}</p></CardContent></Card> : null}
  </div>;
}
