export enum PlayerClass {
  GUNSLINGER = 'GUNSLINGER',
  BERSERKER = 'BERSERKER',
  DESTROYER = 'DESTROYER',
  DEATHBRINGER = 'DEATHBRINGER',
  ASSASSIN = 'ASSASSIN',
  DIVINE_CASTER = 'DIVINE_CASTER',
  NIGHT_RANGER = 'NIGHT_RANGER',
  VANGUARD = 'VANGUARD',
  ELEMENTALIST = 'ELEMENTALIST',
  WARLORD = 'WARLORD',
}

export enum EventType {
  LUNOS = 'LUNOS',
  RIGRETO = 'RIGRETO',
  GARDRON = 'GARDRON',
  MELKAR = 'MELKAR',
  VARGAS = 'VARGAS',
  BELLAMONICA = 'BELLAMONICA',
  SION = 'SION',
  ISTERIA = 'ISTERIA',
  NIDROK = 'NIDROK',
  MORGON = 'MORGON',
  GUILD_DUNGEON = 'GUILD_DUNGEON',
  SATURDAY_EVENT = 'SATURDAY_EVENT',
  ABYSS_1 = 'ABYSS_1',
  ABYSS_1_2 = 'ABYSS_1_2',
  FLOUD = 'FLOUD',
  KRATERIUS = 'KRATERIUS',
  T3_ROTATION = 'T3_ROTATION',
}

export enum EventStatus {
  OPEN = 'OPEN',
  ATTENDANCE_REGISTRATION = 'ATTENDANCE_REGISTRATION',
  FINALIZED = 'FINALIZED',
}

export enum AuctionStatus {
  OPEN = 'OPEN',
  PENDING_REVIEW = 'PENDING_REVIEW',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
  RELISTED = 'RELISTED',
}

export enum AuctionMode {
  STANDARD = 'STANDARD',
  ALL_IN = 'ALL_IN',
  STAFF_REVIEW = 'STAFF_REVIEW',
}

export enum ItemTier {
  T2 = 'T2',
  T3 = 'T3',
  T4 = 'T4',
  LEGENDARY = 'LEGENDARY',
}

export enum ItemType {
  WEAPON = 'WEAPON',
  ARMOR = 'ARMOR',
  ACCESSORY = 'ACCESSORY',
  CELESTIAL_STONE = 'CELESTIAL_STONE',
}

export enum DKPTransactionType {
  EVENT_REWARD = 'EVENT_REWARD',
  AUCTION_LOCK = 'AUCTION_LOCK',
  AUCTION_REFUND = 'AUCTION_REFUND',
  AUCTION_WIN = 'AUCTION_WIN',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
