'use client';

import { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { notifyToast } from '@/components/ui/toaster';
import { type PlayerTrialDraft, useCompleteTrialCheckIn, useCreatePlayerTrial, useDecidePlayerTrial, usePlayerTrialsStaff } from '@/hooks/use-player-trials-api';

const initialDraft: PlayerTrialDraft = {
  playerId: '', objectivePt: 'Validar adaptacao operacional com expectativas claras.', objectiveEn: 'Validate operational fit with clear expectations.', plannedStartAt: '', plannedEndAt: '',
  criteria: [
    { key: 'COMMUNICATION', titlePt: 'Comunicacao', titleEn: 'Communication', descriptionPt: 'Responde combinados e sinaliza impedimentos com antecedencia.', descriptionEn: 'Responds to agreements and flags blockers in advance.', isRequired: true, displayOrder: 0 },
    { key: 'ATTENDANCE', titlePt: 'Participacao combinada', titleEn: 'Agreed participation', descriptionPt: 'Participa dentro da disponibilidade declarada, considerando ausencias.', descriptionEn: 'Participates within declared availability, considering absences.', isRequired: true, displayOrder: 1 },
    { key: 'TEAMWORK', titlePt: 'Trabalho em equipe', titleEn: 'Teamwork', descriptionPt: 'Segue chamadas, pede ajuda e oferece feedback respeitoso.', descriptionEn: 'Follows calls, asks for help, and gives respectful feedback.', isRequired: true, displayOrder: 2 },
  ],
};

export default function StaffTrialsPage() {
  const workspace = usePlayerTrialsStaff();
  const create = useCreatePlayerTrial();
  const complete = useCompleteTrialCheckIn();
  const decide = useDecidePlayerTrial();
  const [draft, setDraft] = useState(initialDraft);
  const [selectedId, setSelectedId] = useState('');
  const [checkInDay, setCheckInDay] = useState(7);
  const [bodyPt, setBodyPt] = useState('');
  const [bodyEn, setBodyEn] = useState('');
  const [internalNote, setInternalNote] = useState('');
  const [decision, setDecision] = useState<'APPROVE' | 'EXTEND' | 'CLOSE'>('APPROVE');
  const [reasonPt, setReasonPt] = useState('');
  const [reasonEn, setReasonEn] = useState('');
  const [extendedEndAt, setExtendedEndAt] = useState('');
  const selected = workspace.data?.trials.find((entry) => entry.trial?.id === selectedId);
  const active = workspace.data?.trials.filter((entry) => entry.trial && ['ACTIVE', 'EXTENDED'].includes(entry.trial.status)) ?? [];
  function patchCriterion(index: number, field: string, value: string) { setDraft((current) => ({ ...current, criteria: current.criteria.map((criterion, criterionIndex) => criterionIndex === index ? { ...criterion, [field]: value } : criterion) })); }

  return <div className="space-y-6"><div><p className="text-sm uppercase text-primary">Trial Staff</p><h1 className="font-[var(--font-cinzel)] text-3xl font-bold">Criterios visiveis e decisoes justificadas</h1><p className="mt-2 max-w-4xl text-sm text-muted-foreground">O player recebe objetivo e criterios antes da avaliacao. Ausencia declarada pausa o periodo; check-ins sao factuais e separados da nota interna. Nada aqui muda loot ou aplica punicao automatica.</p></div>
    <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Em andamento</p><p className="mt-1 text-2xl font-bold">{active.length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Pausados por ausencia</p><p className="mt-1 text-2xl font-bold">{active.filter((entry) => entry.effectiveStatus === 'PAUSED').length}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Regra de seguranca</p><p className="mt-1 text-sm font-semibold">Decisao humana + auditoria</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>Publicar novo trial</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Select value={draft.playerId} onChange={(event) => setDraft((current) => ({ ...current, playerId: event.target.value }))}><option value="">Selecione o player</option>{workspace.data?.players.map((player) => <option key={player.id} value={player.id}>{player.nickname}</option>)}</Select><Input type="date" value={draft.plannedStartAt} onChange={(event) => setDraft((current) => ({ ...current, plannedStartAt: event.target.value }))} /><Input type="date" value={draft.plannedEndAt} onChange={(event) => setDraft((current) => ({ ...current, plannedEndAt: event.target.value }))} /></div><div className="grid gap-3 md:grid-cols-2"><textarea className="min-h-24 rounded-md border border-white/10 bg-background p-3 text-sm" value={draft.objectivePt} onChange={(event) => setDraft((current) => ({ ...current, objectivePt: event.target.value }))} placeholder="Objetivo PT-BR" /><textarea className="min-h-24 rounded-md border border-white/10 bg-background p-3 text-sm" value={draft.objectiveEn} onChange={(event) => setDraft((current) => ({ ...current, objectiveEn: event.target.value }))} placeholder="Objective EN" /></div>{draft.criteria.map((criterion, index) => <div key={criterion.key} className="space-y-3 rounded-md border border-white/10 p-3"><div className="flex items-center gap-2"><Badge tone="blue">{index + 1}</Badge><Input value={criterion.key} onChange={(event) => patchCriterion(index, 'key', event.target.value.toUpperCase())} /></div><div className="grid gap-2 md:grid-cols-2"><Input value={criterion.titlePt} onChange={(event) => patchCriterion(index, 'titlePt', event.target.value)} placeholder="Titulo PT-BR" /><Input value={criterion.titleEn} onChange={(event) => patchCriterion(index, 'titleEn', event.target.value)} placeholder="Title EN" /><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={criterion.descriptionPt} onChange={(event) => patchCriterion(index, 'descriptionPt', event.target.value)} /><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={criterion.descriptionEn} onChange={(event) => patchCriterion(index, 'descriptionEn', event.target.value)} /></div></div>)}<Button disabled={create.isPending || !draft.playerId || !draft.plannedStartAt || !draft.plannedEndAt} onClick={() => create.mutate(draft, { onSuccess: () => { notifyToast({ title: 'Trial publicado para o player.', tone: 'success' }); setDraft(initialDraft); }, onError: () => notifyToast({ title: 'Nao foi possivel publicar o trial.', tone: 'error' }) })}>Publicar criterios e iniciar trial</Button></CardContent></Card>
    <Card><CardHeader><CardTitle>Acompanhar trial</CardTitle></CardHeader><CardContent className="space-y-4"><Select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}><option value="">Selecione um trial</option>{workspace.data?.trials.map((entry) => entry.trial ? <option key={entry.trial.id} value={entry.trial.id}>{entry.trial.player?.nickname ?? entry.trial.playerId} · {entry.effectiveStatus}</option> : null)}</Select>{selected?.trial ? <div className="space-y-4"><div className="rounded-md border border-white/10 p-3"><div className="flex flex-wrap gap-2"><Badge tone={selected.effectiveStatus === 'PAUSED' ? 'blue' : 'gold'}>{selected.effectiveStatus}</Badge><span className="text-sm">fim ajustado {selected.adjustedEndAt ? new Date(selected.adjustedEndAt).toLocaleDateString() : '-'}</span></div><p className="mt-2 text-sm">{selected.trial.objectivePt}</p></div>
      {['ACTIVE', 'EXTENDED'].includes(selected.trial.status) ? <><div className="space-y-3 rounded-md border border-white/10 p-3"><p className="font-semibold">Registrar check-in factual</p><Select value={checkInDay} onChange={(event) => setCheckInDay(Number(event.target.value))}>{[7, 14, 30].map((day) => <option key={day} value={day}>D{day}</option>)}</Select><div className="grid gap-2 md:grid-cols-2"><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={bodyPt} onChange={(event) => setBodyPt(event.target.value)} placeholder="Registro visivel PT-BR" /><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={bodyEn} onChange={(event) => setBodyEn(event.target.value)} placeholder="Player-visible record EN" /></div><textarea className="min-h-20 w-full rounded-md border border-white/10 bg-background p-3 text-sm" value={internalNote} onChange={(event) => setInternalNote(event.target.value)} placeholder="Nota interna opcional (nunca aparece ao player)" /><Button disabled={complete.isPending || bodyPt.trim().length < 3 || bodyEn.trim().length < 3} onClick={() => complete.mutate({ trialId: selected.trial!.id, day: checkInDay, bodyPt, bodyEn, internalNote }, { onSuccess: () => { notifyToast({ title: `Check-in D${checkInDay} registrado.`, tone: 'success' }); setBodyPt(''); setBodyEn(''); setInternalNote(''); }, onError: () => notifyToast({ title: 'Nao foi possivel registrar o check-in.', tone: 'error' }) })}>Registrar check-in</Button></div>
      <div className="space-y-3 rounded-md border border-white/10 p-3"><p className="font-semibold">Decisao manual com motivo</p><Select value={decision} onChange={(event) => setDecision(event.target.value as typeof decision)}><option value="APPROVE">Aprovar</option><option value="EXTEND">Estender</option><option value="CLOSE">Encerrar</option></Select>{decision === 'EXTEND' ? <Input type="date" value={extendedEndAt} onChange={(event) => setExtendedEndAt(event.target.value)} /> : null}<div className="grid gap-2 md:grid-cols-2"><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={reasonPt} onChange={(event) => setReasonPt(event.target.value)} placeholder="Motivo PT-BR" /><textarea className="min-h-20 rounded-md border border-white/10 bg-background p-3 text-sm" value={reasonEn} onChange={(event) => setReasonEn(event.target.value)} placeholder="Reason EN" /></div><Button disabled={decide.isPending || reasonPt.trim().length < 3 || reasonEn.trim().length < 3 || (decision === 'EXTEND' && !extendedEndAt)} onClick={() => decide.mutate({ trialId: selected.trial!.id, decision, reasonPt, reasonEn, extendedEndAt: decision === 'EXTEND' ? extendedEndAt : undefined }, { onSuccess: () => { notifyToast({ title: 'Decisao registrada e auditada.', tone: 'success' }); setReasonPt(''); setReasonEn(''); }, onError: () => notifyToast({ title: 'Nao foi possivel registrar a decisao.', tone: 'error' }) })}>Confirmar decisao</Button></div></> : null}
      <div className="space-y-2"><p className="font-semibold">Historico de check-ins</p>{selected.trial.checkIns.map((checkIn) => <div key={checkIn.id} className="rounded-md border border-white/10 p-3 text-sm"><p>D{checkIn.day} · {checkIn.completedAt ? `concluido em ${new Date(checkIn.completedAt).toLocaleDateString()}` : `previsto para ${new Date(checkIn.scheduledAt).toLocaleDateString()}`}</p>{checkIn.bodyPt ? <p className="mt-1 text-muted-foreground">{checkIn.bodyPt}</p> : null}{checkIn.internalNote ? <p className="mt-1 text-xs text-amber-200">Nota interna: {checkIn.internalNote}</p> : null}</div>)}</div></div> : null}</CardContent></Card>
  </div>;
}
