CREATE TYPE "GuildPulseStatus" AS ENUM ('DRAFT', 'OPEN', 'CLOSED');
CREATE TYPE "GuildPulseParticipationStatus" AS ENUM ('SUBMITTED', 'SKIPPED');
CREATE TYPE "GuildPulseModerationStatus" AS ENUM ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'HIDDEN');
CREATE TABLE "GuildPulseCycle" ("id" TEXT NOT NULL, "titlePt" TEXT NOT NULL, "titleEn" TEXT NOT NULL, "opensAt" TIMESTAMP(3) NOT NULL, "closesAt" TIMESTAMP(3) NOT NULL, "status" "GuildPulseStatus" NOT NULL DEFAULT 'DRAFT', "minGroupSize" SMALLINT NOT NULL DEFAULT 5, "openTextDays" SMALLINT NOT NULL DEFAULT 30, "createdById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GuildPulseCycle_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GuildPulseResponse" ("id" TEXT NOT NULL, "cycleId" TEXT NOT NULL, "belonging" SMALLINT NOT NULL, "clarity" SMALLINT NOT NULL, "workload" SMALLINT NOT NULL, "fun" SMALLINT NOT NULL, "helpSafety" SMALLINT NOT NULL, "openText" TEXT, "openTextExpiresAt" TIMESTAMP(3), "moderationStatus" "GuildPulseModerationStatus" NOT NULL DEFAULT 'NOT_REQUIRED', "moderatedById" TEXT, "moderatedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GuildPulseResponse_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GuildPulseParticipation" ("id" TEXT NOT NULL, "cycleId" TEXT NOT NULL, "playerId" TEXT NOT NULL, "status" "GuildPulseParticipationStatus" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GuildPulseParticipation_pkey" PRIMARY KEY ("id"));
CREATE INDEX "GuildPulseCycle_status_opensAt_closesAt_idx" ON "GuildPulseCycle"("status", "opensAt", "closesAt");
CREATE INDEX "GuildPulseCycle_createdById_idx" ON "GuildPulseCycle"("createdById");
CREATE INDEX "GuildPulseResponse_cycleId_createdAt_idx" ON "GuildPulseResponse"("cycleId", "createdAt");
CREATE INDEX "GuildPulseResponse_moderationStatus_openTextExpiresAt_idx" ON "GuildPulseResponse"("moderationStatus", "openTextExpiresAt");
CREATE INDEX "GuildPulseResponse_moderatedById_idx" ON "GuildPulseResponse"("moderatedById");
CREATE UNIQUE INDEX "GuildPulseParticipation_cycleId_playerId_key" ON "GuildPulseParticipation"("cycleId", "playerId");
CREATE INDEX "GuildPulseParticipation_cycleId_status_idx" ON "GuildPulseParticipation"("cycleId", "status");
CREATE INDEX "GuildPulseParticipation_playerId_createdAt_idx" ON "GuildPulseParticipation"("playerId", "createdAt");
ALTER TABLE "GuildPulseCycle" ADD CONSTRAINT "GuildPulseCycle_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GuildPulseResponse" ADD CONSTRAINT "GuildPulseResponse_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "GuildPulseCycle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GuildPulseResponse" ADD CONSTRAINT "GuildPulseResponse_moderatedById_fkey" FOREIGN KEY ("moderatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GuildPulseParticipation" ADD CONSTRAINT "GuildPulseParticipation_cycleId_fkey" FOREIGN KEY ("cycleId") REFERENCES "GuildPulseCycle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GuildPulseParticipation" ADD CONSTRAINT "GuildPulseParticipation_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
